version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-initdb:/docker-entrypoint-initdb.d  # Mount initialization scripts
    environment:
      MONGO_INITDB_DATABASE: mydatabase  # Database name for initialization

  backend:
    build:
      context: ./Backend
    container_name: backend_container
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase  # Use the initialized database

  frontend:
    build:
      context: ./Frontend
    container_name: frontend_container
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mongo-data: