version: '3.8'
services:
  mongo:
    image: mongo:8.0
    container_name: mongodb_container
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-initdb:/docker-entrypoint-initdb.d  # Mount initialization scripts
    environment:
      MONGO_INITDB_DATABASE: mydatabase  # Database name for initialization

  backend:
    build:
      context: ./Backend
    container_name: backend_container
    depends_on:
      - mongo
    ports:
      - "4002:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
    container_name: frontend_container
    depends_on:
      - backend
    ports:
      - "4001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4002
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped

volumes:
  mongo-data: